steps:
- name: 'python:3.10'
  args:
  - pip
  - install
  - firebase-admin
  - --user
- name: 'python:3.10'
  args:
  - python
  - upload_commands.py
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - actions-spodkast
  - --gen2
  - --set-secrets=OPENAI_KEY=$_OPENAI_KEY
  - --region=europe-west1
  - --source=./actions_spodkast
  - --trigger-http
  - --runtime=python310
  - --entry-point=actions_spodkast
  - --service-account=spodkast-processor-cf@yggdrasil-ai-hermod.iam.gserviceaccount.com
  - --set-env-vars=PROJECT_ID=$PROJECT_ID
  - --project=$PROJECT_ID
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - spodkast-event-manager
  - --gen2
  - --set-secrets=OPENAI_KEY=$_OPENAI_KEY,ELEVENLABS_KEY=$_ELEVENLABS_KEY
  - --region=europe-west1
  - --source=./spodkast_event_manager
  - --trigger-topic=$_EVENT_BUS
  - --runtime=python310
  - --entry-point=spodkast_event_manager
  - --service-account=spodkast-processor-cf@$PROJECT_ID.iam.gserviceaccount.com
  - --set-env-vars=PROJECT_ID=$PROJECT_ID,EVENT_BUS=$_EVENT_BUS,VOICE_INTRODUCTION=$_VOICE_INTRODUCTION,VOICE_SECTION=$_VOICE_SECTION,VOICE_CLOSURE=$_VOICE_CLOSURE
  - --memory=512MiB
  - --project=$PROJECT_ID